converter/accounts/urls.py
from django.contrib.auth import views
from django.contrib.auth.forms import UserCreationForm
from django.urls import path, reverse_lazy
from django.views import generic
from . import views as custom_views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', custom_views.signup, name='signup'),
]

converter/converter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('currency_exchange.urls')),
    path('', include('accounts.urls')),
    path('', include('saved_rates.urls')),

]

converter/currency_exchange/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^currency_table/$', views.currency_table, name='currency_table'),
    url(r'exchange/$', views.exchange, name='exchange'),
    url(r'exchange_table/$', views.exchange_table, name='exchange_table'),
]

converter/saved_rates/urls.py
from django.urls import path, reverse_lazy
from . import views
app_name = 'saved_rates'

urlpatterns = [
    path('saved_rates/', views.saved_rates, name='saved_rates'),
    path('db_save/', views.db_save, name='db_save'),
]

converter/accounts/models.py
from django.db import models

# Create your models here.

converter/currency_exchange/models.py
from django.db import models

# Create your models here.

converter/saved_rates/models.py
from django.db import models

# Create your models here.
class Rates(models.Model):
    class Meta:
        db_table = 'rates'

    user_id = models.CharField(max_length=200)
    body = models.TextField()

converter/accounts/views.py
import requests
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

converter/currency_exchange/views.py
from django.shortcuts import render
import requests
from django.http import HttpResponse
import json
from math import floor

# Create your views here.
def index(request):
    return render(request, 'currency_exchange/index.html')

def currency_table(request):
    return render(request,'currency_exchange/currency_table.html')

def signup_login(request):
    return render(request,'currency_exchange/signup_login.html')

def exchange(request):
    if request.method == 'POST':

        # get data from post request
        amount = request.POST['amount']
        from_convert = request.POST['from_convert']
        to_convert = request.POST['to_convert']
        day = request.POST['day']
        month = request.POST['month']
        year = request.POST['year']

        if len(month) < 2 :
            month = '0' + month

        # send a request to converter api
        url = f'https://free.currencyconverterapi.com/api/v5/convert?q={from_convert}_{to_convert}&compact=ultra&date={year}-{month}-{day}&apiKey=ee368c0a2db8983f80bd'

        response = requests.get(url)
        data = response.json()

        # multiply currency rate by amount
        result = round(data[f'{from_convert}_{to_convert}'][f'{year}-{month}-{day}'], 2) * int(amount)
        
        # return data to ajax success function
        return HttpResponse(result)

def exchange_table(request):
    if request.method == 'POST':

        # get data from post request
        from_convert = request.POST['from_convert']
        to_convert = request.POST['to_convert']
        start_day = request.POST['start_day']
        start_month = request.POST['start_month']
        start_year = request.POST['start_year']

        end_day = request.POST['end_day']
        end_month = request.POST['end_month']
        end_year = request.POST['end_year']

        if len(start_month) < 2 :
            start_month = '0' + start_month

        if len(end_month) < 2 :
            end_month = '0' + end_month

        # send a request to converter api
        url = f'https://free.currencyconverterapi.com/api/v5/convert?q={from_convert}_{to_convert}&compact=ultra&date={start_year}-{start_month}-{start_day}&endDate={end_year}-{end_month}-{end_day}&apiKey=ee368c0a2db8983f80bd'

        response = requests.get(url)
        data = response.json()
        
        # multiply currency rate by amount
        
        # return data to ajax success function
        return HttpResponse(json.dumps(data[f'{from_convert}_{to_convert}']), content_type="application/json")


converter/saved_rates/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from saved_rates.models import Rates

# Create your views here.
def saved_rates(request):
    # get current logged in user
    current_user = request.user

    # get data from db
    rates = Rates.objects.all().filter(user_id = current_user.id)

    context = {
        'rates': rates
    }
    return render(request,'saved_rates/saved_rates.html', context)

def db_save(request):
    if request.method == 'POST':

        # get current user
        current_user = request.user

        #get POST request data
        table_rows = request.POST['text']
        rate = Rates(user_id=current_user.id, body=table_rows)

        # save a conversion record to db
        rate.save()
        return redirect('/saved_rates/')
        

converter/accounts/templates/accounts/signup.html
{% extends 'currency_exchange/layout.html'%}
{% load crispy_forms_tags %}

{% block content%}
<div class="row main-content">
    <div class="col-md-6 mx-auto">
    <div class="card">
        <div class="card-body">
        <h4 class="card-title">Sign up</h4>
        
        <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        
        {{ form|crispy }}
        
        <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
        </div>
        </div>
        </div>
</div>
<script type="text/javascript">
$(document).ready(function() {
    // make current page link active
    $('li.nav-item:first').removeClass('active');
    $('.nav.navbar-nav.ml-auto > li.nav-item:nth-child(2)').addClass('active');
});
</script>
{% endblock%}

converter/currency_exchange/templates/currency_exchange/currency_table.html
{% extends 'currency_exchange/layout.html'%}

{% block content%}
<div class="row main-content">
        <div class="col">
                <form action="" method="POST" class="form-group" id="exchange_form">
                        {% csrf_token %}
                    <h2 class="heading">From</h2>
                    <select name="from_convert" id="from_convert" class="form-control border border-dark">
                        <option value="USD">USD</option>
                        <option value="EUR">EUR</option>
                        <option value="RUB">RUB</option>
                        <option value="UAH">UAH</option>
                    </select>
        </div>
        <div class="col">
                    <h2 class="heading">To</h2>
                    <select name="to_convert" id="to_convert" class="form-control border border-dark">
                        <option value="USD">USD</option>
                        <option value="EUR">EUR</option>
                        <option value="RUB">RUB</option>
                        <option value="UAH">UAH</option> 
                    </select>
        </div>
        <div class="col">
                    <h2 class="heading">Pick a start date</h2>
                    <input id="datepicker_start"/>
        </div>

        <div class="col">
                <h2 class="heading">Pick an end date</h2>
                <input id="datepicker_end"/>
        </div>
            <div class="col-md-12">
                    <input type="submit" name="submit" id="submit_button" class="form-control btn btn-primary" value="Submit">
            </div>
            <br><br>
            </form>
            <div class="col-md-12">
                <form action="/db_save/" method="POST" class="form-group" id="db_save">{% csrf_token %}
                    <input hidden type="text" name="text" value="">
                    <input type="submit" name="submit" id="save-form" class="form-control btn btn-success" value="Save"></form>
            </div>
</div>
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Log in expected</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
          <p>You can't save a rate table without being logged in</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

<br><br>

<script type="text/javascript">

$(document).ready(function() {
    // make current page link active
    $('.navbar-nav.mr-auto > li.nav-item:first').removeClass('active');
    $('.navbar-nav.mr-auto > li.nav-item:nth-child(2)').addClass('active');
});

    // get a date that was week ago
    let min_date = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate()-7);

    // get current date
    current_date = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
    
    let current_day = new Date().getDate();
    let current_month = new Date().getMonth() + 1;
    let current_year = new Date().getFullYear();

    // initialize start and end datepickers
    $('#datepicker_start').datepicker({
            uiLibrary: 'bootstrap4',iconsLibrary: 'fontawesome',
            value: `${current_month}/${current_day-7}/${current_year}`,
            footer: true, modal: true, header: true,
            minDate: min_date,
            maxDate: current_date
    });

    $('#datepicker_end').datepicker({
            uiLibrary: 'bootstrap4',iconsLibrary: 'fontawesome',
            value: `${current_month}/${current_day}/${current_year}`,
            footer: true, modal: true, header: true,
            minDate: min_date,
            maxDate: current_date
    });

    // handling form submit
    $(document).on('submit', '#exchange_form', (e) => {
        e.preventDefault();

        // get date from datepicker
        $('.col-md-10').remove();

        let from_convert = $('#from_convert').val();
        let to_convert = $('#to_convert').val();

        let start_date = $('#datepicker_start').val().split('/');
        let start_day = start_date[1];
        let start_month = start_date[0];
        let start_year = start_date[2];


        let end_date = $('#datepicker_end').val().split('/');
        let end_day = end_date[1];
        let end_month = end_date[0];
        let end_year = end_date[2];
        
        // send ajax request to server side
        $.ajax({
            url: "/exchange_table/",
            type: "POST",
            data: {
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),

                from_convert: from_convert,
                to_convert: to_convert,
                start_day: start_day,
                start_month: start_month,
                start_year: start_year,

                end_day: end_day,
                end_month: end_month,
                end_year: end_year
            },
            success: function(data) {
                // initialize template for a table 
                var template = '';
                
                // insert response data into table rows
                for(var key in data) {
                    template += `<tr class="date_row"><th scope="row" class="date">${key}</th><td class="currency_rate">${data[key]}</td></tr>`;
                }

                var text =`<div class="col-md-10 mx-auto"><table class="table table-bordered table-striped"><thead class="thead table-info"><tr><th scope="col">Date</th><th scope="col">1.00 ${from_convert} to ${to_convert}</th></tr></thead><tbody>${template}</tbody></table></div><br>`;
                
                // append table to body
                $('body').append(text);

                // append rows into hidden input
                $('input[name=text]').val(text);
            },
        });
    });
</script>
{% endblock %}

converter/currency_exchange/templates/currency_exchange/index.html
{% extends 'currency_exchange/layout.html'%}

{% block content%}
<div class="row main-content">
    <div class="col-md-6">
        <form action="" method="POST" class="form-group" id="exchange_table_form">
            {% csrf_token %}
            <h2 class="heading">From</h2>
            <select name="from_convert" id="from_convert" class="form-control border border-dark">
                <option value="USD">USD</option>
                <option value="EUR">EUR</option>
                <option value="RUB">RUB</option>
                <option value="UAH">UAH</option>
            </select>
            <h2 class="heading">To</h2>
            <select name="to_convert" id="to_convert" class="form-control border border-dark">
                <option value="USD">USD</option>
                <option value="EUR">EUR</option>
                <option value="RUB">RUB</option>
                <option value="UAH">UAH</option> 
            </select>
            <h2 class="heading">Pick a currency rate date</h2>
            <input id="datepicker"/>
        </div>
            <div class="col-md-6">
            
            <h2 class="heading">Input amount</h2>
            <input type="text" id="amount" class="form-control border border-dark">
            <h2 class="heading">Output amount</h2>
            <input type="text" id="output_amount" class="form-control border border-dark">
            <br>
            <input type="submit" name="submit" id="submit_button" class="form-control btn btn-primary" value="Submit">
        </form>
        </div>
</div>
<script type="text/javascript">

    let today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
    let min_date = new Date(new Date().getFullYear()-1, new Date().getMonth(), new Date().getDate());
    let current_day = new Date().getDate();
    let current_month = new Date().getMonth() + 1;
    let current_year = new Date().getFullYear();

    $('#datepicker').datepicker({
            uiLibrary: 'bootstrap4',iconsLibrary: 'fontawesome',
            value: `${current_month}/${current_day}/${current_year}`,
            footer: true, modal: true, header: true,
            maxDate: today,
            minDate: min_date,
    });

    $(document).on('submit', '#exchange_table_form', (e) => {
        e.preventDefault();

        // get date from datepicker

        let date = $('#datepicker').val().split('/');
        let day = date[1];
        let month = date[0];
        let year = date[2];


        // send ajax request to server side
        $.ajax({
            url: "/exchange/",
            type: "POST",
            data: {
                amount: $('#amount').val(),
                from_convert: $('#from_convert').val(),
                to_convert: $('#to_convert').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                day: day,
                month: month,
                year: year
            },
            success: function(data) {
                // insert response data into input
                $('input#output_amount').val(data);

            },
        });
    });
</script>
{% endblock%}

converter/currency_exchange/templates/currency_exchange/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'money_icon.png'%}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">    
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'style.css'%}">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <title>Currency Exchange</title>
</head>
<body>
    <header>
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand" href="/">
                    <img src="{%static 'money_icon.png'%}" width="30" height="30" alt="">
                    Currency Rates
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'currency_table' %}">Currency rates table</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'saved_rates:saved_rates' %}">Saved rates</a>
                    </li>
                  </ul>
                  <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    {% else %}
                      <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                      {% endif %}
                    </li>

                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        
                        {% else %}
                          <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
                          {% endif %}
                        </li>
                  </ul>
                </div>
        </nav>
    </header>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script defer src="{% static 'script.js'%}"></script>
</body>
</html>

converter/saved_rates/templates/saved_rates/saved_rates.html
{% extends 'currency_exchange/layout.html'%}
{% load staticfiles %}

{% block content %}
<div class="row main-content">
    {% if user.is_authenticated %}
        {% for rate in rates %}
        <div class="retrieved_data" style="display: none;">
            {{rate.body}}
        </div>
        {% endfor %}
    {% else %}
    <div class="col-md-6 mx-auto">
            <img class="card-img-top" src="{% static 'oops.jpg' %}" alt="Card image" width="400" height="400">
            <div class="card">
                <div class="card-body"><h3>Sorry, you are not logged in</h3></div>
            </div>
    </div>
    {% endif %}
</div>
<script type="text/javascript">
    $(document).ready(function() {

    // make current page link active
    $('.navbar-nav.mr-auto > li.nav-item:first').removeClass('active');
    $('.navbar-nav.mr-auto > li.nav-item:nth-child(3)').addClass('active');
    
    // parse retrieved database data into html
    var text = $('.retrieved_data').text();
    text = $.parseHTML(text);
    $('.row').append(text);
});
</script>
{% endblock %}